[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "oldest-supported-numpy",
    "Cython==3.0.0a10",
    "rapidfuzz_capi==1.0.3"
]
build-backend = "setuptools.build_meta"